// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1BXuFRJ8keVI4st0oB-IEtkKuJzaKXQ',
    appId: '1:1033761409480:web:3e2a232846dcd8b9a598fd',
    messagingSenderId: '1033761409480',
    projectId: 'myapp-4b3db',
    authDomain: 'myapp-4b3db.firebaseapp.com',
    storageBucket: 'myapp-4b3db.appspot.com',
    measurementId: 'G-WNSMGFLR4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflCaGyMA67FfDXRORdP-h-pLNFibhgLI',
    appId: '1:1033761409480:android:afd9a877d6127ca0a598fd',
    messagingSenderId: '1033761409480',
    projectId: 'myapp-4b3db',
    storageBucket: 'myapp-4b3db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0iDMV8fYC_jKWxQDbP3908UcQ8Eikjw',
    appId: '1:1033761409480:ios:71353dd31f1232b5a598fd',
    messagingSenderId: '1033761409480',
    projectId: 'myapp-4b3db',
    storageBucket: 'myapp-4b3db.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0iDMV8fYC_jKWxQDbP3908UcQ8Eikjw',
    appId: '1:1033761409480:ios:54ea1afc524f4555a598fd',
    messagingSenderId: '1033761409480',
    projectId: 'myapp-4b3db',
    storageBucket: 'myapp-4b3db.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
